//
//  TX_WKG_Photo_EditConfig.h
//  SmartCity
//
//  Created by 智享城市iOS开发 on 2018/5/21.
//  Copyright © 2018年 NRH. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface TX_WKG_Photo_EditConfig : NSObject

extern NSString * const TX_WKG_NOTIFICATION_PHOTO_SCRAWL_DEFINIER;

extern NSString * const TX_WKG_NOTIFICATION_PHOTO_MENUOPTIONAL_DEFINIER;


extern NSString * const TX_WKG_NOTIFICATION_VIDEOPLAYER_SHOW_PROGRESS_DEFINER;

extern NSString * const TX_WKG_QXM_VIDEOPASUSE_INTERACTIVE_NOTIFICATION_DEFINER;

extern NSString * const TX_WKG_PHOTO_PUBLISH_NOTIFICATION_DEFINER;

extern NSString * const TX_WKG_PHOTO_INSERT_TEXTWORD_NOTIFICATION_DEFINER;

extern NSString * const TX_WKG_PHOTO_PUBLISH_ELECT_ADDRESS_NOTIFICATION_DEFINER;

extern NSString * const TX_WKG_QMX_VIDEO_PROGRESS_VIEW_HIDDEN_NOTIFICATION_DEFINER;

extern NSString * const TX_WKG_PHOTO_ADD_PASTER_EFFECTIVE_NOTIFICATION_DEFINER;

extern NSString * const TX_WKG_PHOTO_NEWDECOMMEND_ADDLINEWIDTH_MOSAIC_EFFECTIVE_NOTIFICATION_DEFINER;

extern NSString * const  TX_WKG_PHOTO_NEWDECOMMEND_ADPATOR_EFFECTIVE_NOTIFICATION_DEFINER;

@end
